version: '3'

services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./rss-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - MYSQL_DATABASE=RSS
    rss:
        image: rss-dev
        ports:
            - "9999:8080"
            - "4444:4848"
            - "1111:8181"
        links:
            - mysql
        depends_on:
            - mysql
        volumes:
            - ./rss-config:/etc/default/rss
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - BAE_RSS_DATABASE_URL=jdbc:mysql://mysql:3306/RSS
            - BAE_RSS_DATABASE_USERNAME=root
            - BAE_RSS_DATABASE_PASSWORD=my-secret-pw
            - BAE_RSS_DATABASE_DRIVERCLASSNAME=com.mysql.jdbc.Driver
            - BAE_RSS_OAUTH_CONFIG_GRANTEDROLE=admin
            - BAE_RSS_OAUTH_CONFIG_SELLERROLE=Seller
            - BAE_RSS_OAUTH_CONFIG_AGGREGATORROLE=Aggregator
