name: Tests

on:
  push:
    branches:
      - master
      - github-actions

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn test jacoco:report
      - name: Coveralls Report
        run: mvn coveralls:report
